### ISSUE TITLE
Change/obfuscate reserved member attributes that have potential touchpoints with developer code

### ISSUE THREAD

**Issue by evilchia** [cydran/cydran#289]
the "message" member variable is reserved within component but should probably be changed to something much less likely so as to avoid conflicts with outside/extended classes.  An extended class of Component may try and use "message" as a variable but will not be allowed, while there is no indication it would not be allowed.

**Comment by matthewwerny** [comment]
"message" isn't a member variable.  It is a method and needs to retain a clean name of API clarity and consistency.
