### ISSUE TITLE
v() or m() are not being proxied for IMPLICIT component when used as the "empty" type template in c:each scenario

### ISSUE THREAD

**Issue by evilchia** [cydran/cydran#461]
***General Setup***

const x_template = "
  <div c:each="m().someList" c:each:mode="auto">
    <template c:type="empty" c:component="myEmpty"></template>
    <template c:type="item">
      <div>[[v()]]</div>
    </template>
  </div>
";

class ComponentX extends Component {
  constructor(x_template) {
     this.someList = [];
     this.attributeXYZ = "Hello";
  }
}

const emptyTemplate = "<div>[[m().attributeXYZ]]</div>";

builder
  .withPrototype("xcomponent", ComponentX)
  .withImplicit("myEmpty", emptyTemplate)

***Expected Result***
See "Hello" as value when the c:each (m().someList) is empty or null

**Comment by evilchia** [comment]
I understand m() normally NOT proxied to the parent of the "c:each" - we have v() to deal with a value representation but in this particular scenario it makes sense either treat the "empty" template type the same as the "item" type and make v() available _OR_ proxy through an m() representation.  This would apply to IMPLICIT templates as an "empty" type.

**Comment by matthewwerny** [comment]
Apparently, I missed the non-implicit component case.

**Comment by matthewwerny** [comment]
This may have been resolved by the FSM refactor, but an explicit integration test case using the test harness paradigm is needed in order to confirm.

**Comment by matthewwerny** [comment]
I've started work on integration tests for this.

**Comment by matthewwerny** [comment]
This issue has been resolved.
