### ISSUE TITLE
Change Cydran namespace designation from c: to c- and associated references

### ISSUE THREAD

**Issue by evilchia** [cydran/cydran#523]
Cydran attribute references are prefixed with "c:", which presents difficulties to older devices/browsers where there may exist confusion between XML and HTML designations.  Modern browsers do not seem to have this limitation.  A change to a designation without a perceived conflict with XML will nullify most/all of such concerns.  Example: c:each:mode="" would exist as c-each-mode="".

**Comment by matthewwerny** [comment]
Supporting data-c- and c- (or other configured Cydran attribute prefix) would be extremely simple and desirable for those that want 100% HTML specification adhering markup even prior to Cydran doing a semantic pass across the DOM.

**Comment by evilchia** [comment]
Done on Jan 7, 2022 in #523-namespace-delimiter branch

**Comment by matthewwerny** [comment]
Merged
