### ISSUE TITLE
Support valueless attributes for behaviors with default values

### ISSUE THREAD

**Issue by matthewwerny** [cydran/cydran#533]
Currently behaviors require that attributes always include a quoted value.

For example, the current force-focus must be written as follows:

`<input type="text" c:force-focus="true">`

This ticket would extend the definition of behaviors such that optionally a default expression would be part of the interface contract when implementing a behavior.  In the case of force-focus, a default value of true could be provided.  As a result, the equals sign and quoted value would not be required.

This would then allow for markup as follows:

`<input type="text" c:force-focus>`

**Comment by evilchia** [comment]
This didn't get closed with the merge so here it is.
