### ISSUE TITLE
Force focus behavior is broken after FSM lifecycle refactor

### ISSUE THREAD

**Issue by matthewwerny** [cydran/cydran#544]
**Describe the bug**

c:force-focus behavior does not keep the input field focused and only focused when the expression value goes to false and back to true.

**To Reproduce**
Attempt to use the c:force-force behavior on a component

**Expected behavior**
The c:force-focus behavior should force focus on an element conditional on the provided expression.

**Comment by evilchia** [comment]
Apparently this ticket didn't get closed with the merge, so here it is.
