### ISSUE TITLE
Reconsider naming of c-test attribute for alternative item templates in c-each

### ISSUE THREAD

**Issue by matthewwerny** [cydran/cydran#592]
### Summary ###
Developer feedback has suggested that the c-test attribute naming might be confusing to developers using the framework when using the alternatives API for c-each.  He rightly suggested that this could be confused with the behavior of the c-if, given that they do a somewhat similar type of thing in a different context. 

### Potential Risks ###

- If the usage expectations of the IfBehavior change in future releases (unlikely), the common naming could confused developers.

### Perceived Benefits ###
- Better developer experiencing by having arguably more semantic naming choices in the markup API.

**Comment by evilchia** [comment]
c-qualifier might be appropriate as there is also prior semantic art to support it, such as Spring @Qualifier annotation

**Comment by matthewwerny** [comment]
After some deliberation and offline discussion, it was agreed that the issue was more of a lack of documentation that is presented in a high profile manner and some potentially missing validation that would guide the developer to using the APIs correctly.   As such, and due to the c-test parameter being terse and the c-if concept not being exactly the same as c-test, we are going to leave it as c-test.
